#!/usr/bin/perl -l


# Copyright (C) 2015 Bibliotheca Alexandrina <http://www.bibalex.org/>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at
# your option) any later version.

# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


# Initially by yid, with contribution from mam.

# TODO: --without-includes-file, --no-implicit-includes, --no-implicit-exclude-all.

use Cwd qw(abs_path);
use Getopt::Long qw(GetOptions);

$s_hostname = `hostname`;

$s_hostname =~ /(\D+)(\d+)/;
$l = length $2;

Getopt::Long::Configure('gnu_getopt');
GetOptions('m=s' => \$d_hostname, 'help|h!' => \$help, 'without-includes-file' => \$without_includes_file, 'no-implicit-includes' => \$no_implicit_includes, 'no-implicit-exclude-all' => \$no_implicit_exclude_all,);

unless (defined($d_hostname))
{

# If this host has an even hostnum, the pair is + 1 up. Otherwise, - 1
# down. Fairly enough, it is assumed numbers will not overflow and break
# the padding.
if ($2 % 2 == 0)
{

$d_hostname = $1 . sprintf ( "%0${l}d", $2 + 1 );

}
else
{

$d_hostname = $1 . sprintf ( "%0${l}d", $2 - 1 );

}

}

foreach (@ARGV)
{
  # Get the absolute path. Also, collapse successive slashes, trim
  # trailing slash.
  $_ = abs_path("$_");

  $f = "$_";
  unless (-d $f)
  {
    warn    "$f: Not a directory";
    next;
  }

  $f = "$_/.pairsync.includes";
  unless (-f $f && -r $f)
  {
    warn    "$f: Not a regular file, unreadable, or does not exist";
    next;
  }

  `rsync -a --delete --include=/.pairsync.includes --include-from="$_/.pairsync.includes" --exclude="*" "$_/" $d_hostname:"$_/"`;
}
